FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app
COPY . .
RUN pnpm install

RUN curl -L https://dl.dagger.io/dagger/install.sh | sh

ENTRYPOINT ["/bin/sh"]