FROM --platform=linux/amd64 node:20-alpine

RUN apk add --no-cache docker-cli
RUN curl -L https://dl.dagger.io/dagger/install.sh | sh

WORKDIR /app
COPY package*.json .
RUN npm install --save-dev jest
COPY . .

RUN dagger mod init

ENTRYPOINT ["dagger"]