autocommit:
  enabled: true
  branch: ${{ github.ref }}
  message: "fix: [CI-AUTO] Repair {issue} in {files}"
  documentation:
    require: true
    paths:
      - docs/**
      - README.md
safety:
  max_retries: 3
  timeout: 600
  protected_branches:
    - main
    - production