name: Agentic CI

on: [push, pull_request]

jobs:
  self-healing:
    runs-on: ubuntu-latest
    container:
      image: docker.io/areid987/agentic-ci:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Repair Agent
        env:
          APP_ID: ${{ secrets.GH_APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
        run: |
          dagger run \
          --app-id=${APP_ID} \
          --private-key="${APP_PRIVATE_KEY}" \
          repair-agent