name: Auto-Repair CI

on: [push, pull_request]

jobs:
  diagnose-and-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        id: test
        run: npm test
      - name: Auto Repair Loop
        if: failure()
        uses: dagger/dagger-for-github@v5
        with:
          cmd: run repair-agent --retries=3 --push-branch=${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.AGENTIC_CI_PAT }}