name: Self-Healing CI

on: [push, pull_request]

jobs:
  validate-and-repair:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kpenfound/greetings-api/agentic-ci:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Agentic Pipeline
        env:
          GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
        run: |
          dagger run \
          --app-id=${GITHUB_APP_ID} \
          --private-key=${GITHUB_APP_PRIVATE_KEY} \
          agentic-ci repair